config/routes.rb
ShortenUrl::Application.routes.draw do
  get "home/landing"
  resources :links
  get "links/shorten/:uuid" => "links#shorten"

  get "/" => "home#landing"

  

end

app/models/link.rb
class Link < ActiveRecord::Base
  validates_format_of :in_url, :with => URI::regexp(%w(http https))
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def landing
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]

  # GET /links
  # GET /links.json
  def index
    @links = Link.all
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  def shorten
    link = Link.where(:uuid => params[:uuid]).first
    redirect_to link.in_url
  end

  # GET /links/new
  # def new
  def new
    @link = Link.new
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    uuid = SecureRandom.hex(4)
    @link = Link.new(link_params)
    @link.uuid = uuid

    if @link.save
      redirect_to @link
    else
      render :new
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update


    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:in_url, :out_url, :uuid)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/home/landing.html.erb
<h1>Hello World </h1>
<p>down is the lin to our awesome ap</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShortenUrl</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>

<%= link_to 'Show All ', links_path %>
</html>

app/views/layouts/foobar.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShortenUrl</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<h1> foobar </h1>

<%= yield %>

<%= link_to "Links" ,links_path %>

</body>

</html>

app/views/links/_form.html.erb
  <%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="field">
    <%= f.label :in_url %><br>
    <%= f.text_field :in_url %>
    <
  </div>
 <!--  <div class="field">
    <%= f.label :out_url %><br>
    <%= f.text_field :out_url %>
  </div> -->
 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
  <h1>Listing links......</h1>

<table>
  <thead>
    <tr>
      <th>In url</th>
      <th>Out url</th>
      <th>Uuid</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @links.each do |link| %>
      <tr>
        <td><%= link.in_url %></td>
        <!-- <td><%= link.out_url %></td>-->
        <td><%= link.uuid %></td>
        <td><%= link_to 'Show', link %></td>
        <td><%= link_to 'Edit', edit_link_path(link) %></td>
        <td><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Link', new_link_path %>

app/views/links/new.html.erb
<h1>New link</h1>

<%= render 'form' %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>In url:</strong>
  <%= @link.in_url %>
</p>

<p>
  <strong>Out url:</strong>
  <%= @link.out_url %>
</p>

<p>
  <strong>Uuid:</strong>
  <%= @link.uuid %>
</p>

<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>